// <auto-generated />
using System;
using Lektion_SUT24_250414_API_intro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lektion_SUT24_250414_API_intro.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250415095638_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lektion_SUT24_250414_API_intro.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actors = "[\"Leonardo DiCaprio\",\"Joseph Gordon-Levitt\",\"Elliot Page\"]",
                            Director = "Christopher Nolan",
                            Genre = "Science Fiction",
                            Length = new TimeSpan(0, 2, 28, 0, 0),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Actors = "[\"Marlon Brando\",\"Al Pacino\",\"James Caan\"]",
                            Director = "Francis Ford Coppola",
                            Genre = "Crime",
                            Length = new TimeSpan(0, 2, 55, 0, 0),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Actors = "[\"Christian Bale\",\"Heath Ledger\",\"Aaron Eckhart\"]",
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            Length = new TimeSpan(0, 2, 32, 0, 0),
                            Title = "The Dark Knight"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
