// <auto-generated />
using System;
using Lektion_SUT24_250414_API_intro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lektion_SUT24_250414_API_intro.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250416072615_AddedDirector")]
    partial class AddedDirector
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lektion_SUT24_250414_API_intro.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 1970,
                            FirstName = "Christopher",
                            LastName = "Nolan"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 1939,
                            FirstName = "Francis",
                            LastName = "Ford Coppola"
                        });
                });

            modelBuilder.Entity("Lektion_SUT24_250414_API_intro.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actors = "[\"Leonardo DiCaprio\",\"Joseph Gordon-Levitt\",\"Elliot Page\"]",
                            DirectorId = 1,
                            Genre = "Science Fiction",
                            Length = new TimeSpan(0, 2, 28, 0, 0),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Actors = "[\"Marlon Brando\",\"Al Pacino\",\"James Caan\"]",
                            DirectorId = 2,
                            Genre = "Crime",
                            Length = new TimeSpan(0, 2, 55, 0, 0),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Actors = "[\"Christian Bale\",\"Heath Ledger\",\"Aaron Eckhart\"]",
                            DirectorId = 1,
                            Genre = "Action",
                            Length = new TimeSpan(0, 2, 32, 0, 0),
                            Title = "The Dark Knight"
                        });
                });

            modelBuilder.Entity("Lektion_SUT24_250414_API_intro.Models.Movie", b =>
                {
                    b.HasOne("Lektion_SUT24_250414_API_intro.Models.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Lektion_SUT24_250414_API_intro.Models.Director", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
